# Generated by Django 4.2.5 on 2023-09-18 14:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tasktype",
            options={"verbose_name": "task type", "verbose_name_plural": "task types"},
        ),
        migrations.AlterModelOptions(
            name="worker",
            options={
                "ordering": ["position"],
                "verbose_name": "worker",
                "verbose_name_plural": "workers",
            },
        ),
    ]
